### ISSUE TITLE
Need support for Django 1.8

### ISSUE THREAD

**Issue by tieugene** [praekelt/django-simple-autocomplete#21]
1. monkey.py:
   AttributeError: 'Options' object has no attribute 'module_name'.
2. in ModelChoiceField__init__(
   _args, *_kwargs)
   TypeError: Error when calling the metaclass bases
   **init**() got an unexpected keyword argument 'limit_choices_to'
3. views.py", line 3
   from django.utils import simplejson
   ImportError: cannot import name simplejson

Django 1.8.7, Fedora 23 (current stable)

**Comment by tieugene** [comment]
Quick hack for 1st problem:

--- monkey.py.orig      2016-01-11 13:22:20.228463095 +0300
+++ monkey.py   2016-01-11 13:39:10.464235332 +0300
@@ -4,6 +4,7 @@
 from django.forms.models import ModelChoiceField, ModelMultipleChoiceField
 from django.conf import settings
 from django.forms.fields import Field
+from django import VERSION as DJ_VERSION
 
 _simple_autocomplete_queryset_cache = {}
 
@@ -23,7 +24,7 @@
     # Monkey starts here
     if self.__class__ in (ModelChoiceField, ModelMultipleChoiceField):
         meta = queryset.model._meta
-        key = '%s.%s' % (meta.app_label, meta.module_name)
+        key = '%s.%s' % (meta.app_label, meta.module_name if DJ_VERSION < (1, 7) else meta.model_name)
         # Handle both legacy settings SIMPLE_AUTOCOMPLETE_MODELS and new
         # setting SIMPLE_AUTOCOMPLETE.
         models = getattr(
@@ -33,7 +34,7 @@
         if key in models:
             pickled = pickle.dumps((
                 queryset.model._meta.app_label,
-                queryset.model._meta.module_name,
+                queryset.model._meta.module_name if DJ_VERSION < (1, 7) else meta.model_name,
                 queryset.query
             ))
             token = hashlib.md5(pickled).hexdigest()

**Comment by tieugene** [comment]
Patch for #3:
-from django.utils import simplejson
+import simplejson

**Comment by hedleyroos** [comment]
Hi. My notifications weren't coming through for this project. I'll be fixing issues shortly. Sorry for the silence.

**Comment by hedleyroos** [comment]
I've released 1.9. While it only officially supports Django 1.9 it should work with 1.8.

**Comment by amxelemara** [comment]
Is this issue resolved? 
(It looks resolved)
Can someone close this ticket as its misleading.

**Comment by hedleyroos** [comment]
I think adding a test for 1.8 would be best before closing this issue.

**Comment by hedleyroos** [comment]
Closing this since 1.8 is quite old by now.
